// Game data extracted from promti.db
const GAME_DATA = {
  phrases: [
    { id: 1,  phrase: "Шёлковая бочка" },
    { id: 2,  phrase: "Фотограф для фей" },
    { id: 3,  phrase: "Мохнатый шмель" },
    { id: 4,  phrase: "Душистый хмель" },
    { id: 5,  phrase: "Бриллиантовый инжектор" },
    { id: 6,  phrase: "Ночной кашпо" },
    { id: 7,  phrase: "Кузькина мать" },
    { id: 8,  phrase: "Кофе из фанеры" },
    { id: 9,  phrase: "Веер из купюр" },
    { id: 10, phrase: "Фрегат в саду" },
    { id: 11, phrase: "Кислый перец" },
    { id: 12, phrase: "Вареный лось" },
    { id: 13, phrase: "Розовый слон" },
    { id: 14, phrase: "Горькая ваниль" },
    { id: 15, phrase: "Надувной фен" },
    { id: 16, phrase: "Сиплый свист" },
    { id: 17, phrase: "Сиплый свист" },
    { id: 18, phrase: "Пыльный валенок" },
    { id: 19, phrase: "Злая мышь" },
    { id: 20, phrase: "Соловей разбойник" },
    { id: 21, phrase: "Нефритовая клавиатура" },
    { id: 22, phrase: "Пюре из арбуза" },
    { id: 23, phrase: "Ферзь из жвачки" }
  ],

  forbidden_words: [
    { id: 1,  phrase_id: 1,  root: "боч" },
    { id: 2,  phrase_id: 1,  root: "шёлк" },
    { id: 3,  phrase_id: 1,  root: "шелк" },
    { id: 4,  phrase_id: 2,  root: "фото" },
    { id: 5,  phrase_id: 2,  root: "фея" },
    { id: 6,  phrase_id: 2,  root: "фей" },
    { id: 7,  phrase_id: 3,  root: "мох" },
    { id: 8,  phrase_id: 4,  root: "душ" },
    { id: 9,  phrase_id: 4,  root: "дух" },
    { id: 10, phrase_id: 3,  root: "шмел" },
    { id: 11, phrase_id: 4,  root: "хмел" },
    { id: 12, phrase_id: 5,  root: "брлил" },
    { id: 13, phrase_id: 5,  root: "инжек" },
    { id: 14, phrase_id: 6,  root: "ноч" },
    { id: 15, phrase_id: 6,  root: "каш" },
    { id: 16, phrase_id: 7,  root: "кузь" },
    { id: 17, phrase_id: 7,  root: "мат" },
    { id: 18, phrase_id: 7,  root: "мам" },
    { id: 19, phrase_id: 8,  root: "коф" },
    { id: 20, phrase_id: 8,  root: "фан" },
    { id: 21, phrase_id: 9,  root: "веер" },
    { id: 22, phrase_id: 9,  root: "купюр" },
    { id: 23, phrase_id: 10, root: "фрегат" },
    { id: 24, phrase_id: 10, root: "сад" },
    { id: 25, phrase_id: 11, root: "кисл" },
    { id: 26, phrase_id: 11, root: "пер" },
    { id: 27, phrase_id: 12, root: "вар" },
    { id: 28, phrase_id: 12, root: "лос" },
    { id: 29, phrase_id: 13, root: "роз" },
    { id: 30, phrase_id: 13, root: "слон" },
    { id: 31, phrase_id: 14, root: "гор" },
    { id: 32, phrase_id: 14, root: "ванил" },
    { id: 33, phrase_id: 15, root: "дут" },
    { id: 34, phrase_id: 15, root: "дув" },
    { id: 35, phrase_id: 15, root: "фен" },
    { id: 36, phrase_id: 16, root: "свист" },
    { id: 37, phrase_id: 16, root: "сип" },
    { id: 38, phrase_id: 17, root: "звук" },
    { id: 39, phrase_id: 17, root: "свист" },
    { id: 40, phrase_id: 17, root: "сип" },
    { id: 41, phrase_id: 17, root: "хрип" },
    { id: 42, phrase_id: 18, root: "пыл" },
    { id: 43, phrase_id: 18, root: "пыль" },
    { id: 44, phrase_id: 18, root: "вал" },
    { id: 45, phrase_id: 19, root: "био" },
    { id: 46, phrase_id: 19, root: "грыз" },
    { id: 47, phrase_id: 19, root: "зоо" },
    { id: 48, phrase_id: 19, root: "клик" },
    { id: 49, phrase_id: 19, root: "компьютер" },
    { id: 50, phrase_id: 19, root: "манипул" },
    { id: 51, phrase_id: 19, root: "мыш" },
    { id: 52, phrase_id: 19, root: "мышь" },
    { id: 53, phrase_id: 19, root: "числ" },
    { id: 54, phrase_id: 19, root: "зла" },
    { id: 55, phrase_id: 19, root: "зло" },
    { id: 56, phrase_id: 20, root: "солов" },
    { id: 57, phrase_id: 20, root: "разб" },
    { id: 58, phrase_id: 21, root: "нефр" },
    { id: 59, phrase_id: 21, root: "клав" },
    { id: 60, phrase_id: 22, root: "пюр" },
    { id: 61, phrase_id: 22, root: "арб" },
    { id: 62, phrase_id: 23, root: "фер" },
    { id: 63, phrase_id: 23, root: "жва" }
  ]
};
